project:
  type: website
  output-dir: docs

book:
  title: "xyz-book"
  author: "Norah Jones"
  date: "2026/9/17"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    theme: [custom.scss, flatly]  
    gargoyle-fonts: false 
    mainfont: "Arial"      
    sansfont: "sans-serif"
  pdf:
    documentclass: scrreprt



